# Generated by Django 4.2.4 on 2023-09-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_enrol',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='submission_choice',
            old_name='sc_choice',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='submission_choice',
            old_name='sc_subm',
            new_name='submission',
        ),
    ]
